In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
print(np.__version__)

1.26.4

In [3]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [4]:
dataset.head(133)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,46.0,80.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,160.000000,...,27.000000,8100.000000,3.200000,yes,no,no,poor,poor,yes,yes
129,46.0,110.000000,d,0.0,0.0,normal,normal,notpresent,notpresent,130.000000,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,yes
130,46.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,123.000000,...,50.000000,6300.000000,4.800000,no,no,no,yes,poor,no,no
131,46.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,102.000000,...,44.000000,11000.000000,5.400000,no,no,no,yes,poor,no,no
132,46.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no

In [ ]:
dataset

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [ ]:
dataset

In [6]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.97898864 0.97932915 0.98497885 0.98822372
        nan        nan 0.97267592 0.97317808 0.98143051 0.97899003]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [11]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [12]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001301,0.000401,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000802,0.000401,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.018224,0.000934,0.004210,0.000597,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.985075,0.971429,0.968750,0.985075,0.984615,0.978989,0.007317,6
3,0.094383,0.007790,0.003901,0.001360,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.957746,0.968750,0.985075,0.985075,0.979329,0.014636,4
4,0.016630,0.000734,0.004206,0.000507,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.985075,0.985507,0.984615,0.969697,1.000000,0.984979,0.009587,2
5,0.143351,0.010147,0.007115,0.001717,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.971429,0.984615,0.985075,1.000000,0.988224,0.010792,1
6,0.001103,0.000203,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000904,0.000493,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.017526,0.001767,0.003714,0.000514,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985075,0.957746,0.935484,0.985075,1.000000,0.972676,0.023066,8
9,0.140830,0.002114,0.005502,0.000996,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.969697,0.957746,0.968750,0.969697,1.000000,0.973178,0.014152,7
10,0.016619,0.001200,0.003014,0.000776,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.969697,1.000000,0.952381,0.985075,1.000000,0.981431,0.018355,3
11,0.120395,0.014482,0.005308,0.002256,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.971429,0.968750,0.969697,0.985075,0.978990,0.012057,5

In [15]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [18]:
table_pr=pd.DataFrame()

In [19]:
print(X_test)

           age     bp   al   su         bgr    bu   sc         sod       pot  \
132  46.000000   70.0  0.0  0.0  100.000000  47.0  0.5  142.000000  3.500000
309  66.000000   90.0  2.0  0.0  153.000000  76.0  3.3  137.528754  4.627244
334  69.000000   70.0  0.0  0.0   83.000000  42.0  1.2  139.000000  3.700000
196  55.000000  100.0  1.0  4.0  297.000000  53.0  2.8  139.000000  4.500000
246  60.000000   90.0  2.0  0.0  105.000000  53.0  2.3  136.000000  5.200000
..         ...    ...  ...  ...         ...   ...  ...         ...       ...
349  71.000000   70.0  0.0  0.0   81.000000  18.0  0.8  145.000000  5.000000
168  50.000000   80.0  0.0  0.0  137.000000  46.0  0.8  139.000000  5.000000
150  48.000000  100.0  0.0  0.0  103.000000  79.0  5.3  135.000000  6.300000
392  51.492308   60.0  3.0  0.0  148.112676  34.0  1.2  137.528754  4.627244
66   34.000000   60.0  0.0  0.0   91.000000  49.0  1.2  135.000000  4.500000

          hrmo  ...  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  \
132  16.400000  ...        True       True        False       False    False
309  12.518156  ...        True       True        False        True    False
334  16.200000  ...        True       True        False       False    False
196  11.200000  ...        True       True        False       False     True
246  11.100000  ...       False       True        False       False    False
..         ...  ...         ...        ...          ...         ...      ...
349  14.700000  ...        True       True        False       False    False
168  14.100000  ...        True       True        False       False    False
150   6.300000  ...        True       True        False       False     True
392  10.800000  ...       False      False        False       False    False
66   13.500000  ...        True       True        False       False    False

     dm_yes  cad_yes  appet_yes  pe_yes  ane_yes
132   False    False       True   False    False
309   False    False      False   False    False
334   False    False       True   False    False
196    True    False       True   False    False
246   False    False       True   False    False
..      ...      ...        ...     ...      ...
349   False    False       True   False    False
168   False    False       True   False    False
150   False     True      False   False    False
392   False    False       True   False    False
66    False    False       True   False    False

[133 rows x 27 columns]

In [ ]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

In [20]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

C:\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

0.9832615973218556

In [ ]:
table_pr.to_csv("cm.csv",index=False)

In [ ]:
dataset['']
dataset['Predicted']=grid_predictions

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))